// TODO: Testejar que, ...
// hi hagi els elements necessaris al DOM
// inicialment estigui ocult
// cridi a submit quan es prem el botó
// el submit ..
//   faci el submit event
//   amagui el welcome screen
//   llenci mostrarEsperando
//   que cridi a controlarMovimiento
// controlarMovimientos ...
//   crida a vigila cada segon  
//   vigila ...
//     fa bé doGeolocation
//     recupera valors correctes
//     llenci positionChange
//   
// Generated by CoffeeScript 1.6.2
describe("The esperandoView should",function(){
    beforeEach(function(){
        spyOn(console, 'error').andCallThrough();
    });

    it("should have the apropriate DOM elements", function(){
        expect(window.app.esperandoView.el[0].nodeName).toEqual('SECTION');
        expect(window.app.esperandoView.$el).toHaveClass('esperando');
    });

    it ("should be initially invisible", function(){
        expect(window.app.esperandoView.$el).toHaveClass('template');
    });

    it ("should become visible when the user connects", function(){
        ChatApp.vent.trigger('mostrarEsperando');       
        
        expect(window.app.welcomeView.$el).toHaveClass('template');
        expect(window.app.esperandoView.$el).not.toHaveClass('template');
        expect(window.app.esperandoView.$el).not.toBeHidden(); // already tested in the welcome view
    });

    it ("should stop waiting (hide itself and show user list, messages and inputArea) when message received", function  () {
        expect($('section.userList')).toHaveClass('template');
        expect($('section.messages')).toHaveClass('template');
        expect($('section.inputArea')).toHaveClass('template');
        
        ChatApp.vent.trigger('dejarEsperar');
        
        expect(window.app.esperandoView.$el).toBeHidden();  
        expect($('section.userList')).not.toHaveClass('template');
        expect($('section.messages')).not.toHaveClass('template');
        expect($('section.inputArea')).not.toHaveClass('template');
    });

    it("should remove old messages", function  () {
        expect($('section.messages ul.no-padding li:not(:first)').length).toBe(0);
        expect($('section.messages ul.no-padding li:first')).not.toBe(undefined);
    })
    
    it ("should become visible again (show itself and hide user list, messages and inputArea)) if the other user disconnects", function(){
        ChatApp.vent.trigger('mostrarEsperando');       
        
        expect(window.app.welcomeView.$el).toHaveClass('template');
        expect(window.app.esperandoView.$el).not.toHaveClass('template');
        expect(window.app.esperandoView.$el).not.toBeHidden(); // already tested in the welcome view
    });

    it("should not have triggered any error", function  () {
        expect(console.error).not.toHaveBeenCalled();
    });

    it ("should be left as original", function(){
        $("section.welcome").removeClass('template');
        $("section.welcome").show();
        $("section.esperando").addClass('template');
    });
});