// Generated by CoffeeScript 1.6.2
describe("Greeter", function () {
    it("says hello", function () {
        return expect(new myapp.Greeter().greet("World")).toEqual("Hello World!");
    });
    return it("does not says bye bye", function () {
        return expect(new myapp.Greeter().greet("World")).not.toEqual("Bye Bye!");
    });
});

describe("Prova test", function () {
    beforeEach(function () {
        return this.date = new Date(2009, 9, 2, 22, 14, 45);
    });
    afterEach(function () {
        return delete this.date;
    });
    it(" %Y should Return Full Year ", function () {
        var year;

        year = Date.formats.Y(this.date);
        expect(year).toEqual(jasmine.any(Number));
        return expect(year).toEqual(2009);
    });
    it("", function () {
        var month;

        month = Date.formats.m(this.date);
        expect(month).toEqual(jasmine.any(String));
        return expect(month).toEqual("10");
    });
    it("", function () {
        return expect(Date.formats.d(this.date)).toEqual("02");
    });
    return it("", function () {
        return expect(Date.formats.y(this.date)).toEqual(9);
    });
});
